### ISSUE TITLE
Clarify Context#destroyBean behavior

### ISSUE THREAD

**Issue by beikov** [eclipse-ee4j/cdi#427] opened 2020-03-02 15:52 UTC
When wanting to delete a bean instance from the HTTP session that hasn't been accessed via Contex#get in that request, destroy doesn't do anything when using Weld.

Is that intended?

I debugged and it seems to be due to the session context being lazy.

**Comment by manovotn** [comment] 2020-03-02 16:00
So what happens is that bean creation in general is lazy - until you try and use the bean, no contextual instance is created for normal scoped beans (do not confuse this with the injected proxy, that one is created of course!).
And from your description, I gather that's exactly the case - you have an injected proxy, but you never invoked a method on that bean so far.

In other words, you are attempting to destroy a bean which was never created in the first place - therefore nothing happens, which is intended.

**Comment by beikov** [comment] 2020-03-02 16:03
Not exactly. In a previous request the bean instance is created and in a subsequent request I want to delete it, but within that request the bean hasn't been used yet.

**Comment by manovotn** [comment] 2020-03-02 16:12
Ok, then can you provide some code snippet showing how exactly you try to destroy the bean?

**Comment by beikov** [comment] 2020-03-02 16:21
So my code looks like this

```java
        BeanManager beanManager = BeanManagerProvider.getInstance().getBeanManager();
        DeltaSpikeContextExtension extension = beanManager.getExtension(DeltaSpikeContextExtension.class);
        Bean<Object> bean = getBean(name, beanManager);
        Context context = beanManager.getContext(bean.getScope());

        // We need to access the bean first so that it is populated in the request cache
        context.get(bean);
        if (context instanceof AlterableContext) {
            ((AlterableContext) context).destroy(bean);
        } else if (context instanceof AbstractContext) {
            ((AbstractContext) context).destroy(bean);
        } else if (context.equals(extension.getConversationContext())) {
            extension.getConversationContext().destroy(bean);
        } else if (context.equals(extension.getViewAccessScopedContext())) {
            extension.getViewAccessScopedContext().destroy(bean);
        } else if (context.equals(extension.getWindowContext())) {
            extension.getWindowContext().destroy(bean);
        } else {
            throw new IllegalArgumentException("Unsupported scope type which can't be used to destroy beans: " + context);
        }
```

Without the `context.get(bean);` the deletion won't work in the following scenario.

HTTP-Request 1 creates a session and a bean with name e.g. "abc".
HTTP-Request 2 tries to delete that bean.

In Weld, this doesn't work because there is a request level cache for beans. If that cache does not contain the bean that should be deleted, it's not removed from the HTTP Session.

**Comment by manovotn** [comment] 2020-03-02 16:40
Interesting, for the sake of curiosity, can you try to perform the destruction with `Instance.destroy()` instead?

**Comment by beikov** [comment] 2020-03-02 16:44
Not sure what you mean. Do you mean `javax.enterprise.inject.Instance#destroy`? That requires the actual object instance to destroy. To get that, I have to resolve the object.

**Comment by manovotn** [comment] 2020-03-02 18:58
Yes, that's what I mean and no you don't need actual instance - you need its proxy for normal scoped beans.

From CDI specification: `The bean instance passed to destroy() should be a dependent scoped bean instance obtained from the same Instance object, or a client proxy for a normal scoped bean.`

**Comment by mkouba** [comment] 2020-03-02 19:28
@manovotn @beikov from what I see in the code the `Instance#destroy()` would not help either. It's very likely caused by the "attributes lazy fetching" optimization, see https://issues.redhat.com/browse/WELD-1970 for more details. There is [a config option](https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/config/ConfigurationKey.java#L178-L183) that can be used to disable this optimization. Unfortunately, it's not documented properly. See the [Weld configuration docs](https://docs.jboss.org/weld/reference/latest/en-US/html/configure.html#_weld_configuration) for more info.

**Comment by beikov** [comment] 2020-03-02 22:43
AFAICS, the problem is that the bean store does not contain the bean that should be destroyed in https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/contexts/beanstore/AttributeBeanStore.java#L158
Accessing it via the get method before will populate the bean in the bean store and cause it to be properly removed.

**Comment by mkouba** [comment] 2020-03-03 07:06
Yes, that's the consequence of the optimization. If enabled the attributes are read lazily, ie. when a bean instance is needed. However, when disabled all relevant attributes are copied from the session to a local bean store when the session context is initialized.

**Comment by beikov** [comment] 2020-03-03 07:32
Would you say that this behavior is correct with respect to the CDI specification or is this a bug in Weld and the CDI spec should further clarify this and maybe add a TCK test?

**Comment by mkouba** [comment] 2020-03-03 07:54
I'd say that:
1. Strictly speaking, it's a Weld bug. I've created https://issues.redhat.com/browse/WELD-2615.
2. The use case is quite unusual.
3. There is no need to clarify the spec.
4. I don't think this deserves a TCK test due to (2).

**Comment by manovotn** [comment] 2020-03-03 08:38
Let's move any further discussion under the [Weld issue](https://issues.redhat.com/browse/WELD-2615). I'll close this one.

**Closed by manovotn** 2020-03-03 08:38 UTC
